# Generated by Django 4.2.3 on 2023-07-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erwandjango", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("subject", models.CharField(max_length=50)),
                ("tsenum", models.CharField(max_length=30)),
            ],
        ),
    ]
