# Generated by Django 4.2.3 on 2023-07-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erwandjango", "0002_teacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="people",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name="Student",
        ),
        migrations.DeleteModel(
            name="Teacher",
        ),
    ]
